### ISSUE TITLE
동물별 데이터 그래프 수정

### ISSUE THREAD

**Issue by breadrose** [goodroad/goodroad.github.io#4]
http://goodroad.co.kr/html/indicators/indicator_animal.html
![default](https://cloud.githubusercontent.com/assets/26083598/24575976/34f27eda-16ee-11e7-900d-f91b3149b743.jpg)
지금 원그래프에 마우스 올리면 나오는 테그들이 막막 떠있는거 보이죠!
이거 어떻게 해주실거에요? 수정해주세요~

**Comment by tries12qw** [comment]
d3pie 라이브러리 버그입니다...
https://github.com/benkeen/d3pie/issues/86

문제되는 부분 주석처리하였지만 

마우스 움일때마다 툴팁이 따라오지않게 되었습니다.
